# Writes the CPP files to a local cache - eventually will hold binary files (I hope)... then we don't
# need to do it this way.
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "func-adl-server.fullname" . }}-cpp-writer
  labels:
    app: {{ template "func-adl-server.name" . }}
    chart: {{ template "func-adl-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    # Why do I have to repeat this - this seems crazy do this twice here. Three times in one file...
    matchLabels:
      app: {{ template "func-adl-server.name" . }}-cpp-writer
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "func-adl-server.name" . }}-cpp-writer
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.images.func_adl }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          command:
            - python
            - translate_ast_to_cpp_rabbit.py 
            - {{ .Release.Name }}-rabbitmq
            - user
            - RABBITMQ_PASSWORD
          env:
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-rabbitmq
                  key: rabbitmq-password
          volumeMounts:
            - mountPath: /cache
              name: cpp-cache
      volumes:
        - name: cpp-cache
          persistentVolumeClaim:
            claimName: {{ template "func-adl-server.fullname" . }}-cpp-cache
