# Serve the root file results over http
# If there is no ingester then you can tied this to an exteral_ip by defining that. It will
# only be port 80 if that happens.
#
apiVersion: v1
kind: Service
metadata:
  name: {{ template "func-adl-server.fullname" . }}-http-results
  labels:
    app: {{ template "func-adl-server.name" . }}
    chart: {{ template "func-adl-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
{{- if .Values.external_interface.external_ip }}
  type: ClusterIP
{{- else }}
  type: NodePort
{{- end }}
  ports:
    - name: http
      port: 80
{{- if not .Values.external_interface.external_ip }}
      nodePort: {{ .Values.external_interface.web_port }}
{{- end }}
      protocol: TCP
{{- if .Values.external_interface.external_ip }}
  externalIPs: [ {{ .Values.external_interface.external_ip }} ]
{{- end}}
  selector:
    app: {{ template "func-adl-server.name" . }}-http-results
    release: {{ .Release.Name }}
