# Run a simple nginx server to dish out results as http read-only.
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "func-adl-server.fullname" . }}-http-results
  labels:
    app: {{ template "func-adl-server.name" . }}
    chart: {{ template "func-adl-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "func-adl-server.name" . }}-http-results
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "func-adl-server.name" . }}-http-results
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: as-http-results
          image:  {{ .Values.images.results_web_server }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: xrootd-cache
            - mountPath: /etc/nginx/conf.d
              name: nginx-cfg
      volumes:
        - name: xrootd-cache
          persistentVolumeClaim:
            claimName: {{ template "func-adl-server.fullname" . }}-results
        - name: nginx-cfg
          configMap:
            name:  {{ template "func-adl-server.fullname" . }}-http-config