# The xROOTT server needs to be declared as a service for this puppy to work.
apiVersion: v1
kind: Service
metadata:
  name: {{ template "func-adl-server.fullname" . }}-web
  labels:
    app: {{ template "func-adl-server.name" . }}
    chart: {{ template "func-adl-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: 8000
      nodePort: 30000
      targetPort: 8000
      protocol: TCP
  selector:
    app: {{ template "func-adl-server.name" . }}-web
    release: {{ .Release.Name }}
