# The xROOTT server needs to be declared as a service for this puppy to work.
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
  labels:
    app: {{ template "func-adl-server.name" . }}
    chart: {{ template "func-adl-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  # TODO: Need to figure out how to use NodePort (or similar) to expose this to the outside world.
  type: NodePort
  ports:
    - port: 8000
      nodePort: 30000
  selector:
    name: {{ .Release.Name }}-web
