# Run a simple version of rabbitmq
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "func-adl-server.fullname" . }}-xrootd-results
  labels:
    app: {{ template "func-adl-server.name" . }}
    chart: {{ template "func-adl-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    # Why do I have to repeat this - this seems crazy do this twice here. Three times in one file...
    matchLabels:
      app: {{ template "func-adl-server.name" . }}-xrootd-results
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "func-adl-server.name" . }}-xrootd-results
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: as-xrootd-results
          image: {{ .Values.images.xrootd_results }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          cports:
            - name: xrootd
              containerPort: 1094
            - name: http
              containerPort: 8001
          volumeMounts:
            - mountPath: /data/xrd
              name: xrootd-cache
      volumes:
        - name: xrootd-cache
          emptyDir: {}
