# Run the executable in the old-style binary files.
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "func-adl-server.fullname" . }}-xaod-runner
  labels:
    app: {{ template "func-adl-server.name" . }}
    chart: {{ template "func-adl-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.scaling.xaod_runner }}
  selector:
    # Why do I have to repeat this - this seems crazy do this twice here. Three times in one file...
    matchLabels:
      app: {{ template "func-adl-server.name" . }}-xaod-runner
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "func-adl-server.name" . }}-xaod-runner
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.images.xaod_runner }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          command:
            - /bin/bash
            - -c 
            - "source /home/atlas/release_setup.sh; python cmd_runner_rabbit.py {{ .Release.Name }}-rabbitmq {{ template "func-adl-server.fullname" . }}-xrootd-results user RABBITMQ_PASSWORD"
          env:
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-rabbitmq
                  key: rabbitmq-password
          volumeMounts:
            - mountPath: /cache
              name: cpp-cache
            - mountPath: /data
              name: rucio-data
      volumes:
        - name: cpp-cache
          persistentVolumeClaim:
            claimName: {{ template "func-adl-server.fullname" . }}-cpp-cache
        - name: rucio-data
          hostPath:
            path: {{ .Values.rucio.local_data_cache }}
