# The PVC for the C++ code cache
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: {{ template "func-adl-server.name" . }}
    chart: {{ template "func-adl-server.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "func-adl-server.fullname" . }}-cpp-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
