dependencies:
  - name: rabbitmq
    version: 6.1.*
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: mongodb
    version: 4.0.*
    repository: https://kubernetes-charts.storage.googleapis.com/
  # - name: nginx-ingress
  #   version: 0.24.*
  #   repository: https://kubernetes-charts.storage.googleapis.com/
