# Default values for func-adl-server.

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  path: /
  # hosts:
  #   - localhost

resources: {}
  # Not going to restrict here: this server should be able to run on a laptop
  # and on bigger iron.

nodeSelector: {}

tolerations: []

affinity: {}

# Configure the mongodb guy
# TODO: Store the database somewhere that will stick around between invokations.
#       Needs to be around as long as we store results in the xrootd results guy.
mongodb:
  persistence:
    enabled: false
  usePassword: false

# TODO: if we do an "upgrade" of the helm charte, a new secret for rabbitmq is generated, which is distributed to only
# the new apps. If rabbitmq does not restart, it uses old scret and no one can get in anymore.
# TODO: this does not alter the password.
rabbitmq:
  password: leftfoot1
