# Default values for func-adl-server.

external_interface:
  # When we have to re-write a url for external viewing, what should we use as our cluster node name?
  node_name: localhost
  # Expose xrootd with our results on this port externally.
  xrootd_port: 30001
  # Expose web service where queries are submitted
  web_port: 30000

# Configure the mongodb guy
mongodb:
  persistence:
    enabled: false
  usePassword: false

rabbitmq:
  password: leftfoot1

# The default container tags used to power this.
# Pull policy translates to the usual Kubernetes policy.
images:
  pullPolicy:
  func_adl: gordonwatts/func_adl:latest
  desktop_rucio: gordonwatts/func-adl-rucio:latest
  func_adl_utils: gordonwatts/func_adl_request_broker:latest
  xrootd_results: gordonwatts/func_adl_results_xrootd:latest
  xaod_runner: gordonwatts/func_adl_cpp_runner:latest

scaling:
  rucio_dwonloader: 2