# Default values for func-adl-server.

external_interface:
  # When we have to re-write a url for external viewing, what should we use as our cluster node name?
  node_name: localhost
  # Expose xrootd with our results on these ports externally (first is for xrootd, second is http access)
  xrootd_port: 30001
  # Expose web service where queries are submitted
  web_port: 30000

rucio:
  # Just make sure that rucio exists. Otherwise the logic can get very complex
  dummy: False

# Configure the mongodb guy
# Persistence is false b.c. true does not work on Windows at the moment.
mongodb:
  persistence:
    enabled: false
  usePassword: false

# Use a username and password so we know how to get into the montior
# port when we expose it. Username is "user".
rabbitmq:
  rabbitmq:
    password: leftfoot1
  persistence:
    enabled: false

# The default container tags used to power this.
# Pull policy translates to the usual Kubernetes policy.
# Use IfNotPresent if you want to use an image already on the machine.
images:
  pullPolicy:
  func_adl: gordonwatts/func_adl:1.0.0
  desktop_rucio: gordonwatts/func-adl-rucio:1.0.0
  func_adl_xcache: gordonwatts/func-adl-rucion2n:1.0.2
  func_adl_utils: gordonwatts/func_adl_request_broker:1.0.0
  xrootd_results: gordonwatts/func_adl_results_xrootd:1.0.0
  xaod_runner: gordonwatts/func_adl_cpp_runner:1.0.0
  results_web_server: nginx:stable

scaling:
  # For a running server 2-4 depending on your network connection
  rucio_downloader: 1
  # Depends how busy things are - but a few.
  xaod_runner: 1